queue_rules:
  - name: default
    merge_conditions:
      - "#approved-reviews-by>=0"

pull_request_rules:
  - name: automatic merge on label
    conditions:
      - label=queue
    actions:
      queue:
        name: default
